spring:
  application:
    name: VideoCallApp
  datasource:
    url: jdbc:mysql://localhost:3306/db_video_call
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

uploads:
  directory: uploads/images

#server:
#  port: 8443  # Standard HTTPS port
#  ssl:
#    key-store-type: JKS
#    key-store: classpath:keystore.jks
#    key-store-password: 297i!54ZgmeJD$])
#    key-alias: tomcat
#  address: 0.0.0.0  # Bind to all network interfaces

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.ensamc: DEBUG  # Replace with your actual package name